const PRODUCTS = [
  { id: 'ledgermax-pro', name: 'LedgerMax Pro', price: 4999 },
  { id: 'gstwise-billing', name: 'GSTWise Billing', price: 1499 },
  { id: 'account-plus', name: 'Account Plus', price: 999 },
  { id: 'shieldguard-av', name: 'ShieldGuard AV', price: 221 },
  { id: 'shieldguard-av-6m', name: 'ShieldGuard AV — 6 Month Plan', price: 149 },
  { id: 'quickshield-6m', name: 'QuickShield Pro — 6 Months', price: 179 },
  { id: 'safenet-security', name: 'SafeNet Security', price: 311 },
  { id: 'securemax-infiniti', name: 'SecureMax Infiniti', price: 2372 },
  { id: 'peoplepulse-hrms', name: 'PeoplePulse HRMS', price: 45 },
  { id: 'teamtrack-hr', name: 'TeamTrack HR', price: 50 },
  { id: 'saleflow-crm', name: 'SaleFlow CRM', price: 2099 },
  { id: 'leadbridge-crm', name: 'LeadBridge CRM', price: 1680 },
  { id: 'kylas-style-crm', name: 'GrowthCRM Unlimited', price: 12999 },
  { id: 'retailpro-pos', name: 'RetailPro POS', price: 9000 },
  { id: 'shopmate-erp', name: 'ShopMate One ERP', price: 8474 },
  { id: 'invoicehub', name: 'InvoiceHub', price: 699 },
  { id: 'payroll-bill', name: 'PayRoll Bill', price: 3700 },
  { id: 'billmaster-pro', name: 'BillMaster Pro', price: 4500 },
  { id: 'edumanage-pro', name: 'EduManage Pro', price: 7670 },
  { id: 'campus-sync', name: 'CampusSync', price: 3000 },
  { id: 'schooledge', name: 'SchoolEdge ERP', price: 500000 },
  { id: 'workflow-suite', name: 'WorkFlow Suite', price: 2570 },
  { id: 'collabdesk', name: 'CollabDesk', price: 1549 },
  { id: 'taskflow-pro', name: 'TaskFlow Pro', price: 999 },
  { id: 'vga-cable-1.5m', name: 'VGA Cable 1.5m', price: 120 },
  { id: 'vga-cable-3m', name: 'VGA Cable 3m', price: 165 },
  { id: 'usb-cable-micro-1m', name: 'USB 2.0 Cable (Micro USB) 1m', price: 100 },
  { id: 'usb-cable-type-c-1m', name: 'USB Type-C Cable 1m', price: 149 },
  { id: 'usb-extension-1m', name: 'USB Extension Cable 1m', price: 110 },
  { id: 'hdmi-usb-adapter', name: 'USB to HDMI Adapter', price: 199 },
];
